_extends: reporanger/superpowers

merges:
  - action: delete_branch

comments:
  # spam removal
  - action: delete_comment
    pattern: "+1"
  - action: delete_comment
    pattern: /^:.+?:$/i
  - action: delete_comment
    pattern: $PROFANITY

