_extends: reporanger/superpowers

labels:
  dependencies: merge

merges:
  - action: delete_branch

comments:
  # spam removal
  - action: delete_comment
    pattern: "+1"
  - action: delete_comment
    pattern: /^:.+?:$/i
  - action: delete_comment
    pattern: $PROFANITY

commits:
  - action: label
    user: dependabot-preview[bot]
    labels:
      - maintenance

sponsor_labels:
  - sponsor
