pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
    actions:
      queue:
        method: squash
        name: default
  - name: Automatic dependency merge
    conditions:
      - author~=^dependabot\[bot\]$
      - base=main
    actions:
      queue:
        method: merge
        name: default
        
queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"