permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

title: Journey
description: A media database like IMDb, but run through GitHub and deployed on Jekyll.

plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-mentions
  - jekyll-octicons

repository: sudojunior/journey

defaults:
  - scope:
      path: ""
    values:
      layout: default

jekyll-spaceship:
  processors:
    - mathjax-processor
    - polyfill-processor
    - media-processor
    - emoji-prossor
    - element-processor
    - mermaid-processor