baseurl: /journey
permalink: pretty
exclude:
  - docs/*
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

title: Journey
description: A media database like IMDb, but run through GitHub and deployed on Jekyll.

plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-octicons

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
