permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - tests/
  - vendor/

title: Journey
description: A media database like IMDb, but run through GitHub and deployed on Jekyll.

plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-octicons

repository: sudojunior/journey

defaults:
  - scope:
      path: ""
    values:
      layout: default
