name: Jekyll

on:
  pull_request:
    paths-ignore:
      - docs/**

jobs:
  # doctor:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.6
  #     - run: bundle install
  #     - run: bundle exec jeykll doctor --trace
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Dependencies
        run: bundle install
      - name: Build Site (Dry Run)
        run: bundle exec jekyll build --trace --safe
